release:
  # draft: true
  prerelease: auto
before:
  hooks:
    - go mod tidy
builds:
  - binary: upsnap
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/seriousm4x/upsnap/pb.Version={{ .Version }}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm
archives:
  - format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Version }}"
changelog:
  sort: asc
