# Generated by Django 3.1.3 on 2020-11-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='mac',
            field=models.CharField(max_length=17),
        ),
    ]
