# Generated by Django 3.1.3 on 2020-11-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wol', '0002_auto_20201115_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
