# Generated by Django 3.1.3 on 2020-11-16 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wol', '0003_device_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='status',
        ),
    ]
