# Generated by Django 3.2.7 on 2021-09-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wol', '0007_device_scheduled_wake'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ping_interval', models.PositiveSmallIntegerField(default=5)),
                ('enable_notifications', models.BooleanField(default=True)),
                ('enable_console_logging', models.BooleanField(default=True)),
                ('sort_by', models.SlugField(default='name')),
            ],
        ),
    ]
