# Generated by Django 3.2.7 on 2021-09-27 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wol', '0008_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='ping_interval',
        ),
    ]
