# Generated by Django 3.1.3 on 2020-11-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100)),
                ('ip', models.GenericIPAddressField()),
                ('mac', models.SlugField(max_length=17)),
            ],
        ),
    ]
