# Generated by Django 3.1.5 on 2021-01-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wol', '0004_remove_device_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='netmask',
            field=models.CharField(default='255.255.255.0', max_length=15),
        ),
    ]
