# Generated by Django 3.2.7 on 2021-09-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wol', '0006_websocket'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='scheduled_wake',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
