# Generated by Django 3.2.7 on 2021-09-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wol', '0009_remove_settings_ping_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='enable_console_logging',
            field=models.BooleanField(default=False),
        ),
    ]
