# Generated by Django 3.2.7 on 2021-09-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wol', '0010_alter_settings_enable_console_logging'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='scan_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
