# Generated by Django 3.2.12 on 2022-02-20 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wol', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='enable_console_logging',
        ),
    ]
