# Generated by Django 4.0.2 on 2022-02-18 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wol', '0002_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wol.port'),
        ),
    ]
