# Generated by Django 4.0.2 on 2022-02-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wol', '0003_device_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='port',
        ),
        migrations.AddField(
            model_name='device',
            name='port',
            field=models.ManyToManyField(blank=True, null=True, to='wol.Port'),
        ),
    ]
