# Generated by Django 4.0.2 on 2022-02-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wol', '0005_alter_port_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='port',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='device',
            name='port',
            field=models.ManyToManyField(to='wol.Port'),
        ),
    ]
