# Generated by Django 4.0.2 on 2022-02-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wol', '0006_alter_port_unique_together_alter_device_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='port',
            field=models.ManyToManyField(blank=True, to='wol.Port'),
        ),
    ]
