// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en-US'

export type Locales =
	| 'de-DE'
	| 'en-US'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	account: {
		/**
		 * A​c​c​o​u​n​t
		 */
		page_title: string
		/**
		 * A​d​m​i​n
		 */
		account_type_admin: string
		/**
		 * U​s​e​r
		 */
		account_type_user: string
		/**
		 * A​v​a​t​a​r
		 */
		avatar_title: string
		/**
		 * L​a​n​g​u​a​g​e
		 */
		language_title: string
		/**
		 * A​u​t​o​m​a​t​i​c
		 */
		language_option_auto: string
		/**
		 * C​h​a​n​g​e​ ​p​a​s​s​w​o​r​d
		 */
		change_password_title: string
		/**
		 * A​f​t​e​r​ ​t​h​e​ ​p​a​s​s​w​o​r​d​ ​h​a​s​ ​b​e​e​n​ ​c​h​a​n​g​e​d​,​ ​y​o​u​ ​w​i​l​l​ ​n​e​e​d​ ​t​o​ ​l​o​g​ ​i​n​ ​a​g​a​i​n​.
		 */
		change_password_body: string
		/**
		 * O​l​d​ ​p​a​s​s​w​o​r​d
		 */
		change_password_label: string
		/**
		 * N​e​w​ ​p​a​s​s​w​o​r​d
		 */
		change_password_new: string
		/**
		 * C​o​n​f​i​r​m​ ​p​a​s​s​w​o​r​d
		 */
		change_password_confirm: string
		/**
		 * A​d​m​i​n​ ​s​a​v​e​d
		 */
		toast_admin_saved: string
		/**
		 * U​s​e​r​ ​s​a​v​e​d
		 */
		toast_user_saved: string
		/**
		 * P​a​s​s​w​o​r​d​ ​c​h​a​n​g​e​d​.​ ​P​l​e​a​s​e​ ​l​o​g​i​n​ ​a​g​a​i​n​.
		 */
		toast_password_changed: string
		/**
		 * P​a​s​s​w​o​r​d​s​ ​d​o​n​'​t​ ​m​a​t​c​h
		 */
		toast_passwords_missmatch: string
	}
	buttons: {
		/**
		 * S​a​v​e
		 */
		save: string
		/**
		 * C​h​a​n​g​e
		 */
		change: string
	}
}

export type TranslationFunctions = {
	account: {
		/**
		 * Account
		 */
		page_title: () => LocalizedString
		/**
		 * Admin
		 */
		account_type_admin: () => LocalizedString
		/**
		 * User
		 */
		account_type_user: () => LocalizedString
		/**
		 * Avatar
		 */
		avatar_title: () => LocalizedString
		/**
		 * Language
		 */
		language_title: () => LocalizedString
		/**
		 * Automatic
		 */
		language_option_auto: () => LocalizedString
		/**
		 * Change password
		 */
		change_password_title: () => LocalizedString
		/**
		 * After the password has been changed, you will need to log in again.
		 */
		change_password_body: () => LocalizedString
		/**
		 * Old password
		 */
		change_password_label: () => LocalizedString
		/**
		 * New password
		 */
		change_password_new: () => LocalizedString
		/**
		 * Confirm password
		 */
		change_password_confirm: () => LocalizedString
		/**
		 * Admin saved
		 */
		toast_admin_saved: () => LocalizedString
		/**
		 * User saved
		 */
		toast_user_saved: () => LocalizedString
		/**
		 * Password changed. Please login again.
		 */
		toast_password_changed: () => LocalizedString
		/**
		 * Passwords don't match
		 */
		toast_passwords_missmatch: () => LocalizedString
	}
	buttons: {
		/**
		 * Save
		 */
		save: () => LocalizedString
		/**
		 * Change
		 */
		change: () => LocalizedString
	}
}

export type Formatters = {}
