// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en-US'

export type Locales =
	| 'de-DE'
	| 'en-US'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	home: {
		/**
		 * G​r​o​u​p​s
		 */
		order_groups: string
		/**
		 * N​a​m​e
		 */
		order_name: string
		/**
		 * I​P
		 */
		order_ip: string
		/**
		 * O​r​d​e​r
		 */
		order_tooltip: string
		/**
		 * N​o​ ​d​e​v​i​c​e​s​ ​h​e​r​e​.
		 */
		message_no_devices: string
		/**
		 * A​d​d​ ​y​o​u​r​ ​f​i​r​s​t​ ​d​e​v​i​c​e
		 */
		message_add_first_device: string
		/**
		 * P​l​e​a​s​e​ ​a​s​k​ ​t​h​e​ ​a​d​m​i​n​ ​t​o​ ​g​r​a​n​t​ ​y​o​u​ ​p​e​r​m​i​s​s​i​o​n​s​ ​t​o​ ​e​x​i​s​t​i​n​g​ ​d​e​v​i​c​e​s​ ​o​r​ ​t​o​ ​c​r​e​a​t​e​ ​n​e​w​ ​o​n​e​s​.
		 */
		message_grant_permissions: string
	}
	account: {
		/**
		 * A​c​c​o​u​n​t
		 */
		page_title: string
		/**
		 * A​d​m​i​n
		 */
		account_type_admin: string
		/**
		 * U​s​e​r
		 */
		account_type_user: string
		/**
		 * A​v​a​t​a​r
		 */
		avatar_title: string
		/**
		 * L​a​n​g​u​a​g​e
		 */
		language_title: string
		/**
		 * A​u​t​o​m​a​t​i​c
		 */
		language_option_auto: string
		/**
		 * C​h​a​n​g​e​ ​p​a​s​s​w​o​r​d
		 */
		change_password_title: string
		/**
		 * A​f​t​e​r​ ​t​h​e​ ​p​a​s​s​w​o​r​d​ ​h​a​s​ ​b​e​e​n​ ​c​h​a​n​g​e​d​,​ ​y​o​u​ ​w​i​l​l​ ​n​e​e​d​ ​t​o​ ​l​o​g​ ​i​n​ ​a​g​a​i​n​.
		 */
		change_password_body: string
		/**
		 * O​l​d​ ​p​a​s​s​w​o​r​d
		 */
		change_password_label: string
		/**
		 * N​e​w​ ​p​a​s​s​w​o​r​d
		 */
		change_password_new: string
		/**
		 * C​o​n​f​i​r​m​ ​p​a​s​s​w​o​r​d
		 */
		change_password_confirm: string
		/**
		 * A​d​m​i​n​ ​s​a​v​e​d
		 */
		toast_admin_saved: string
		/**
		 * U​s​e​r​ ​s​a​v​e​d
		 */
		toast_user_saved: string
		/**
		 * P​a​s​s​w​o​r​d​ ​c​h​a​n​g​e​d​.​ ​P​l​e​a​s​e​ ​l​o​g​i​n​ ​a​g​a​i​n​.
		 */
		toast_password_changed: string
		/**
		 * P​a​s​s​w​o​r​d​s​ ​d​o​n​'​t​ ​m​a​t​c​h
		 */
		toast_passwords_missmatch: string
	}
	buttons: {
		/**
		 * S​a​v​e
		 */
		save: string
		/**
		 * C​h​a​n​g​e
		 */
		change: string
	}
}

export type TranslationFunctions = {
	home: {
		/**
		 * Groups
		 */
		order_groups: () => LocalizedString
		/**
		 * Name
		 */
		order_name: () => LocalizedString
		/**
		 * IP
		 */
		order_ip: () => LocalizedString
		/**
		 * Order
		 */
		order_tooltip: () => LocalizedString
		/**
		 * No devices here.
		 */
		message_no_devices: () => LocalizedString
		/**
		 * Add your first device
		 */
		message_add_first_device: () => LocalizedString
		/**
		 * Please ask the admin to grant you permissions to existing devices or to create new ones.
		 */
		message_grant_permissions: () => LocalizedString
	}
	account: {
		/**
		 * Account
		 */
		page_title: () => LocalizedString
		/**
		 * Admin
		 */
		account_type_admin: () => LocalizedString
		/**
		 * User
		 */
		account_type_user: () => LocalizedString
		/**
		 * Avatar
		 */
		avatar_title: () => LocalizedString
		/**
		 * Language
		 */
		language_title: () => LocalizedString
		/**
		 * Automatic
		 */
		language_option_auto: () => LocalizedString
		/**
		 * Change password
		 */
		change_password_title: () => LocalizedString
		/**
		 * After the password has been changed, you will need to log in again.
		 */
		change_password_body: () => LocalizedString
		/**
		 * Old password
		 */
		change_password_label: () => LocalizedString
		/**
		 * New password
		 */
		change_password_new: () => LocalizedString
		/**
		 * Confirm password
		 */
		change_password_confirm: () => LocalizedString
		/**
		 * Admin saved
		 */
		toast_admin_saved: () => LocalizedString
		/**
		 * User saved
		 */
		toast_user_saved: () => LocalizedString
		/**
		 * Password changed. Please login again.
		 */
		toast_password_changed: () => LocalizedString
		/**
		 * Passwords don't match
		 */
		toast_passwords_missmatch: () => LocalizedString
	}
	buttons: {
		/**
		 * Save
		 */
		save: () => LocalizedString
		/**
		 * Change
		 */
		change: () => LocalizedString
	}
}

export type Formatters = {}
